### ISSUE TITLE
Solving the problem having more than 9 volumes

### ISSUE THREAD

**Issue by FabianZihlmann** [PitWenkin/check_snmp_synology#4]
Change the line 434, then the code is working with more than 9 volumes
storageID[$i]=$(echo "$syno_diskspace" | grep "= \"\?/${storageName[$i]}\"\??" | cut -d "=" -f1 | rev | cut -d "." -f1 | rev)

=> additional ? 

Hope that helps other people as well.
Thanks for your work
Best regards
Fabian

**Comment by PitWenkin** [comment]
Hi @FabianZihlmann,
I will take a look at this, but I currently have no environment with more then 5 volumes …

**Comment by FabianZihlmann** [comment]
With the codeline above it works. Feel free to update the code.
Best regards
Fabian
